service: app-nexura
runtime: php82

runtime_config:
  document_root: public

env_variables:
  DB_DNS: "/cloudsql/potent-impulse-415917:us-central1:nexura-mysql-db"
  DB_USER: "dev-jesus-zapata"
  DB_PASSWORD: "r+fo_n&:*-nd@qLd"
  DB_NAME: "nexura-bd"

entrypoint:
  serve public/index.php
